# -*- coding: utf-8 -*-
"""K-parafac.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/103n5_vCpnJH5EsYQlMubEWrkqg1TBX_Z
"""

pip install eem-python

from pathlib import Path
import re
import numpy as np
import pandas as pd
from google.colab import drive
drive.mount('/content/drive')

"""**STEP 1: Read the EEM data and build-up 3D datasets including em, ex and metadata**"""

# Reader eem tables into 2D matrix
def read_eem_table(fp: Path):
    header1 = pd.read_csv(fp, nrows=1, header=None)
    ex = pd.to_numeric(header1.iloc[0, 1:], errors="coerce").values.astype(float)

    df = pd.read_csv(fp, skiprows=2, header=None)
    em = pd.to_numeric(df.iloc[:, 0], errors="coerce").values.astype(float)
    z  = df.iloc[:, 1:].apply(pd.to_numeric, errors="coerce").to_numpy(dtype=float)

    z = np.nan_to_num(z, nan=0.0)
    # Confirmed with Bri that all files are already blank-subtracted, negative values can appear.
    # Clamp to non-negative values for nonnegative PARAFAC.
    z[z < 0] = 0.0

    # z is (n_em, n_ex) -> return (n_ex, n_em) for stacking
    return z.T, ex, em

from eempy.eem_processing import EEMDataset, PARAFAC
data_dir = Path("/content/drive/My Drive/LBNL Research/Romy/ENIGMA/Enrichments/Fresh vs Recycled necromass/EEMs")
files = sorted(data_dir.glob("Data_*.csv"))

# Exclude abnormal files
bad_files = {
    "Data_BlankSub_Graph_S1_D06B_DNA.csv", # most files have 71 EM points; this one only have 59)
    "Data_BlankSub_Graph_S1_D06B_CW.csv",}  # This one seems to have extremely high intensity compared to others

files_train = [fp for fp in files if fp.name not in bad_files]
print("Training files:", len(files_train))

eem_list, sample_ids = [], []
ex_ref, em_ref = None, None

for fp in files_train:
    eem_ex_by_em, ex, em = read_eem_table(fp)

    if ex_ref is None:
        ex_ref, em_ref = ex, em
    else:
        assert np.array_equal(ex, ex_ref), f"Excitation grid mismatch in {fp.name}"
        assert np.array_equal(em, em_ref), f"Emission grid mismatch in {fp.name}"

    eem_list.append(eem_ex_by_em)
    sample_ids.append(fp.stem)

eem_stack = np.stack(eem_list, axis=0)  # (n_samples, n_ex, n_em)
dataset_train = EEMDataset(eem_stack=eem_stack, ex_range=ex_ref, em_range=em_ref, index=sample_ids)

print("dataset_train:", dataset_train.eem_stack.shape)

"""**STEP 2 Pre-processing: inner filter effect (IFE) correction, Rayleigh and Raman scattering removal, wavelength range etc.**"""

# fill the masked Rayleigh bands ("zero", "linear", "cubic", "nan") for first-order and second-order scatterings.
# didn't correct for inner filter effect (there's no absorbance data from Bri)
# all parameters selected based on default values
dataset_proc = dataset_train.rayleigh_scattering_removal(
    width_o1=10, width_o2=10,
    interpolation_method_o1="linear",
    interpolation_method_o2="linear",
    inplace=False
).raman_scattering_removal(
    width=5,
    interpolation_method="linear",
    interpolation_dimension="2d",
    inplace=False
).cutting(
    ex_min=200, ex_max=400,
    em_min=300, em_max=500,
    inplace=False
)

print("After preprocessing:", dataset_proc.eem_stack.shape)

"""# **Optional manual peak picking**"""

# Set up the peak point
peak_fi, ex_actual, em_actual = dataset_proc.peak_picking(ex=350, em=450)
print("Peak picked at:", ex_actual, em_actual)
print(peak_fi.head())

# Regional integration
# sum fluorescence over a rectangle: Ex [250,300], Em [380,450]
# dataset_proc.eem_stack is (n_samples, n_ex, n_em)
def regional_integration_manual(dataset, ex_min, ex_max, em_min, em_max):
    X = dataset.eem_stack
    ex = np.asarray(dataset.ex_range)
    em = np.asarray(dataset.em_range)

    ex_mask = (ex >= ex_min) & (ex <= ex_max)
    em_mask = (em >= em_min) & (em <= em_max)

    vals = X[:, ex_mask, :][:, :, em_mask].sum(axis=(1, 2))
    return pd.Series(vals, index=dataset.index, name="regional_integration")

ri = regional_integration_manual(dataset_proc, ex_min=250, ex_max=300, em_min=380, em_max=450)
print(ri.head())

metrics = pd.concat(
    [
        peak_fi.rename(columns={peak_fi.columns[0]: "peak_350_450"}),
        ri.to_frame("region_250_300__380_450"),
    ],
    axis=1
)

display(metrics.head())

metrics_log = metrics.copy()
metrics_log["peak_350_450_log10"] = np.log10(metrics_log["peak_350_450"] + 1)
metrics_log["region_log10"] = np.log10(metrics_log["region_250_300__380_450"] + 1)

display(metrics_log.head())

def regional_mean_manual(dataset, ex_min, ex_max, em_min, em_max):
    X = dataset.eem_stack
    ex = np.asarray(dataset.ex_range)
    em = np.asarray(dataset.em_range)
    ex_mask = (ex >= ex_min) & (ex <= ex_max)
    em_mask = (em >= em_min) & (em <= em_max)
    block = X[:, ex_mask, :][:, :, em_mask]
    return pd.Series(block.mean(axis=(1,2)), index=dataset.index, name="regional_mean")

ri_mean = regional_mean_manual(dataset_proc, 250, 300, 380, 450)
metrics["region_mean_250_300__380_450"] = ri_mean

import re

def parse_sample_id(s):
    m = re.search(r"_S1_([^_]+)_(.+)$", s)
    if not m:
        return pd.Series({"sample_group": None, "fraction": None})
    return pd.Series({"sample_group": m.group(1), "fraction": m.group(2)})

meta = metrics.index.to_series().apply(parse_sample_id)
metrics2 = pd.concat([meta, metrics], axis=1)
metrics2

"""# **Parafac**"""

from eempy.eem_processing import PARAFAC, SplitValidation

# Fit unified PARAFAC
parafac = PARAFAC(
    n_components=3,
    solver="hals",
    init="svd",
    max_iter_nnls=300,
    max_iter_als=500,
    random_state=0,
)
parafac.fit(dataset_proc)

# Split validation (stability check)
validator = SplitValidation(
    base_model=parafac,
    n_splits=4,
    combination_size="half",
    rule="random",
    random_state=0,
)
validator.fit(dataset_proc)
similarities = validator.compare_parafac_loadings()

# print the excitation-loading similarity table
print("Excitation loading similarities:")
display(similarities[0])

# print the emission-loading similarity table
print("Emission loading similarities:")
display(similarities[1])

from eempy.plot import plot_eem, plot_fi, plot_loadings, plot_fmax, plot_eem_stack

# Compare a raw EEM vs processed EEM (same sample index)
# choose which sample to visualize
i = 4

plot_eem(
    dataset_train.eem_stack[i],
    dataset_train.ex_range,
    dataset_train.em_range,
    title=f"Raw EEM (sample {i})",
    display=True
)

plot_eem(
    dataset_proc.eem_stack[i],
    dataset_proc.ex_range,
    dataset_proc.em_range,
    title=f"Processed EEM (sample {i})",
    display=True
)

# Plot PARAFAC loadings
plot_loadings({"PARAFAC": parafac})

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from textwrap import shorten
from eempy.plot import plot_eem_stack

# 1) Clean titles, split by "_" into a table you can inspect/sort
prefix = "Data_BlankSub_Graph_S1_"

raw_titles = list(dataset_train.index)
clean_titles = [t[len(prefix):] if t.startswith(prefix) else t for t in raw_titles]

# Optional: keep only samples whose cleaned title starts with "T"
sel = [i for i, t in enumerate(clean_titles) if t.lower().startswith("t")]

parts = [clean_titles[i].split("_") for i in sel]
max_parts = max(len(p) for p in parts) if parts else 0

title_df = pd.DataFrame(parts, columns=[f"part_{k+1}" for k in range(max_parts)])
title_df.insert(0, "orig_index", [raw_titles[i] for i in sel])
title_df.insert(1, "clean_title", [clean_titles[i] for i in sel])
title_df.insert(2, "row_id", sel)

# 2) Rename columns
rename_map = {
    "part_1": "time_point",
    "part_2": "recycled",
    "part_3": "organism",
    "part_4": "oxygen",
}
title_df = title_df.rename(columns={k: v for k, v in rename_map.items() if k in title_df.columns})

# 3) Standardize organism labels
title_df["organism"] = (title_df["organism"].replace({"arthro1": "arthro", "pseudo1": "pseudo"}))
title_df.loc[title_df["oxygen"] == "redo", "oxygen"] = np.nan
title_df["plot_name"] = (
    title_df[["recycled", "organism", "oxygen"]]
    .apply(lambda r: "_".join([str(x) for x in r if pd.notna(x) and str(x) != ""]), axis=1)
)
# 4) Organize plot order (customize as needed)
sort_cols = [c for c in ["time_point", "recycled", "organism", "oxygen"] if c in title_df.columns]
# fallback in case some columns are missing
if not sort_cols:
    sort_cols = [c for c in title_df.columns if c.startswith("part_")]
title_df = title_df.sort_values(sort_cols, kind="mergesort").reset_index(drop=True)

# (Optional) view or save this table
display(title_df)
# title_df.to_csv("eem_titles_parsed.csv", index=False)

from textwrap import shorten
from eempy.plot import plot_eem_stack

prefix = "Data_BlankSub_Graph_S1_"
clean  = [s.replace(prefix, "") for s in list(dataset_train.index)]

sel = [i for i, s in enumerate(clean) if s.lower().startswith("t")]
X = dataset_train.eem_stack[sel]
titles = [shorten(clean[i], 24, placeholder="…") for i in sel]

n_cols = 6
n = len(sel)
n_rows = int(np.ceil(n / n_cols))

out = plot_eem_stack(
    eem_stack=X,
    ex_range=np.asarray(dataset_train.ex_range),
    em_range=np.asarray(dataset_train.em_range),
    titles=titles,
    n_cols=n_cols,
    auto_intensity_range=True,
    cbar=True,
    cbar_fraction=0.04,
    figure_size=(12, 1.7 * n_rows),   # << tighter rows (strong lever)
    plot_x_axis_label=False,
    plot_y_axis_label=False,
)

fig, axes = out[0], np.array(out[1]).ravel()

# IMPORTANT: disable constrained layout if plot_eem_stack enabled it
try:
    fig.set_constrained_layout(False)
except Exception:
    pass

# now this should actually take effect
fig.subplots_adjust(wspace=0.1, hspace=0.1, top=0.95, bottom=0.06)

plt.show()

import re
import numpy as np
import matplotlib.pyplot as plt
from textwrap import shorten

# ----------------------------
# 1) Select samples starting with T/t and clean names
# ----------------------------
prefix = "Data_BlankSub_Graph_S1_"
names  = list(dataset_train.index)
clean  = [s.replace(prefix, "") for s in names]

# keep only those starting with T/t
sel = [(i, clean[i]) for i in range(len(clean)) if clean[i].lower().startswith("t")]

# extract timepoint key: T0, T1, T2, T4, T5 (case-insensitive)
def get_Tkey(s):
    m = re.match(r'^(t\d+)', s.lower())
    return m.group(1).upper() if m else None

# group indices by T key
groups = {}
for i, cname in sel:
    k = get_Tkey(cname)
    if k is not None:
        groups.setdefault(k, []).append(i)

# order rows as requested (only keep those that exist)
row_order = [k for k in ["T0", "T1", "T2", "T4", "T5"] if k in groups]

# ----------------------------
# 2) Build subplot grid (rows=timepoints, cols=max samples in a row)
# ----------------------------
n_rows = len(row_order)
n_cols = max(len(groups[k]) for k in row_order)

ex = np.asarray(dataset_train.ex_range)
em = np.asarray(dataset_train.em_range)

fig, axes = plt.subplots(
    n_rows, n_cols,
    figsize=(3.2 * n_cols, 2.4 * n_rows),
    squeeze=False
)

cmap = "jet"

# ----------------------------
# 3) Plot each EEM (INDIVIDUAL scale per subplot)
# ----------------------------
for r, key in enumerate(row_order):
    idxs = groups[key]
    for c in range(n_cols):
        ax = axes[r, c]
        if c >= len(idxs):
            ax.axis("off")
            continue

        i = idxs[c]
        Z = dataset_train.eem_stack[i]      # (n_ex, n_em)
        Zplot = Z.T                         # (n_em, n_ex) so x=ex, y=em

        vmin = float(np.nanmin(Zplot))
        vmax = float(np.nanmax(Zplot))

        im = ax.imshow(
            Zplot,
            origin="lower",
            aspect="auto",
            extent=[ex.min(), ex.max(), em.min(), em.max()],
            cmap=cmap,
            vmin=vmin, vmax=vmax
        )

        title = shorten(clean[i], width=28, placeholder="…")
        ax.set_title(title, fontsize=9)

        # wider colorbar for each subplot
        cb = fig.colorbar(im, ax=ax, fraction=0.06, pad=0.02)
        cb.ax.tick_params(labelsize=8)

        # keep only leftmost y tick labels and bottom row x tick labels
        if c != 0:
            ax.set_ylabel("")
            ax.tick_params(axis="y", labelleft=False)
        if r != n_rows - 1:
            ax.set_xlabel("")
            ax.tick_params(axis="x", labelbottom=False)

    # row label on the far-left subplot
    axes[r, 0].set_ylabel(f"{key}\nEmission (nm)", fontsize=10)

# bottom-row x label only (leftmost bottom subplot)
axes[n_rows - 1, 0].set_xlabel("Excitation (nm)", fontsize=10)

# tighten spacing between rows/cols
fig.subplots_adjust(wspace=0.15, hspace=0.25, top=0.93, bottom=0.07)

plt.show()

import re
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib.gridspec import GridSpec
from textwrap import shorten

# Assumes title_df already has columns:
# - row_id (int) -> index into dataset_train.eem_stack
# - clean_title (str)
# - time_point (e.g., T0, T1, T2...)
# - plot_name (e.g., fresh_arthro_aer or fresh_arthro if oxygen missing)

def tp_num(tp):
    m = re.match(r"^T(\d+)$", str(tp).upper().strip())
    return int(m.group(1)) if m else 10**9

title_df = title_df.copy()
title_df["time_point"] = title_df["time_point"].astype(str).str.upper().str.strip()

# ---- timepoint order (T0 first) ----
tps = sorted(title_df["time_point"].dropna().unique(), key=tp_num)

# ---- columns for matched plot_name (exclude T0) ----
col_order = (
    title_df.loc[title_df["time_point"] != "T0", "plot_name"]
    .dropna()
    .unique()
)
col_order = sorted(col_order)

# ---- lookup grid for non-T0: (time_point, plot_name) -> row_id ----
grid = (
    title_df.loc[title_df["time_point"] != "T0"]
    .dropna(subset=["time_point", "plot_name", "row_id"])
    .drop_duplicates(subset=["time_point", "plot_name"])  # if duplicates, keep first
    .pivot(index="time_point", columns="plot_name", values="row_id")
)

# ---- T0 samples (free-form row) ----
t0_df = title_df.loc[title_df["time_point"] == "T0"].dropna(subset=["row_id"])
t0_ids = t0_df["row_id"].astype(int).tolist()
t0_titles = t0_df["clean_title"].tolist()

# ---- plotting helper ----
ex = np.asarray(dataset_train.ex_range)
em = np.asarray(dataset_train.em_range)
cmap = "jet"

def plot_one(ax, sample_idx, title):
    Z = dataset_train.eem_stack[int(sample_idx)]
    Zplot = Z.T
    vmin = float(np.nanmin(Zplot))
    vmax = float(np.nanmax(Zplot))
    im = ax.imshow(
        Zplot,
        origin="lower",
        aspect="auto",
        extent=[ex.min(), ex.max(), em.min(), em.max()],
        cmap=cmap,
        vmin=vmin, vmax=vmax
    )
    ax.set_title(shorten(title, width=32, placeholder="…"), fontsize=9)
    cb = plt.colorbar(im, ax=ax, fraction=0.06, pad=0.02)
    cb.ax.tick_params(labelsize=8)
    return im

# ---- layout sizes ----
main_rows = [tp for tp in tps if tp != "T0"]
n_rows_main = len(main_rows)
n_cols_main = len(col_order)

n_cols_t0 = max(len(t0_ids), 1)  # avoid zero
has_t0 = len(t0_ids) > 0

# Figure width: use the larger of the two blocks so it looks consistent
fig_w = 3.2 * max(n_cols_main, n_cols_t0, 1)
fig_h = 2.4 * (n_rows_main + (1 if has_t0 else 0))

fig = plt.figure(figsize=(fig_w, fig_h))
gs = GridSpec(
    nrows=(n_rows_main + (1 if has_t0 else 0)),
    ncols=max(n_cols_main, n_cols_t0, 1),
    figure=fig
)

row_offset = 0

# ---- T0 row at the TOP (no empty columns) ----
if has_t0:
    for c in range(n_cols_t0):
        ax = fig.add_subplot(gs[0, c])
        plot_one(ax, t0_ids[c], f"T0 | {t0_titles[c]}")
        if c != 0:
            ax.tick_params(axis="y", labelleft=False)
    # label on first axis
    fig.axes[0].set_ylabel("T0\nEmission (nm)", fontsize=10)
    row_offset = 1

# ---- Main grid (T1..T5) ----
for r, tp in enumerate(main_rows):
    for c, pname in enumerate(col_order):
        ax = fig.add_subplot(gs[r + row_offset, c])

        if (tp not in grid.index) or (pname not in grid.columns) or pd.isna(grid.loc[tp, pname]):
            ax.axis("off")
            continue

        i = int(grid.loc[tp, pname])
        plot_one(ax, i, f"{tp} | {pname}")

        if c != 0:
            ax.tick_params(axis="y", labelleft=False)
        if r != n_rows_main - 1:
            ax.tick_params(axis="x", labelbottom=False)

    # row label
    first_ax = fig.add_subplot(gs[r + row_offset, 0])
    first_ax.set_ylabel(f"{tp}\nEmission (nm)", fontsize=10)
    first_ax.set_frame_on(False)  # don't draw a second axis frame
    first_ax.set_xticks([]); first_ax.set_yticks([])

# bottom-left x label
# Find the last plotted row's first column axis (best-effort)
# (If it's off, you can just add a global xlabel with fig.text instead.)
fig.text(0.5, 0.02, "Excitation (nm)", ha="center", fontsize=10)

fig.subplots_adjust(wspace=0.15, hspace=0.25, top=0.95, bottom=0.06)
plt.show()

import re
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib.gridspec import GridSpec
from textwrap import shorten

def tp_num(tp):
    m = re.match(r"^T(\d+)$", str(tp).upper().strip())
    return int(m.group(1)) if m else 10**9

def plot_by_recycled(title_df, dataset_train, recycled_value, figure_title=None):
    """
    Make one figure for a given recycled group (e.g., 'fresh' or 'recyc'),
    keeping the same layout logic:
      - T0 row plotted separately (only its own columns)
      - rows ordered by time point (T0 -> ...)
      - columns are plot_name (within this recycled group only)
      - subplot titles are plot_name only (T0 uses clean_title)
      - one clean row label per row on the left
    """
    df = title_df.copy()

    # keep only this recycled group
    df = df.loc[df["recycled"].astype(str).str.lower() == recycled_value.lower()].copy()

    # normalize time_point
    df["time_point"] = df["time_point"].astype(str).str.upper().str.strip()

    # time order
    tps = sorted(df["time_point"].dropna().unique(), key=tp_num)
    main_rows = [tp for tp in tps if tp != "T0"]

    # column order (plot_name) excluding T0
    col_order = sorted(df.loc[df["time_point"] != "T0", "plot_name"].dropna().unique())

    # grid lookup for non-T0
    grid = (
        df.loc[df["time_point"] != "T0"]
        .dropna(subset=["time_point", "plot_name", "row_id"])
        .drop_duplicates(subset=["time_point", "plot_name"])  # if duplicates, keep first
        .pivot(index="time_point", columns="plot_name", values="row_id")
    )

    # T0 row samples (within this recycled group)
    t0_df = df.loc[df["time_point"] == "T0"].dropna(subset=["row_id"])
    t0_ids = t0_df["row_id"].astype(int).tolist()
    t0_titles = t0_df["clean_title"].tolist()
    has_t0 = len(t0_ids) > 0

    # plotting helpers
    ex = np.asarray(dataset_train.ex_range)
    em = np.asarray(dataset_train.em_range)
    cmap = "jet"

    def plot_one(ax, sample_idx, title):
        Z = dataset_train.eem_stack[int(sample_idx)]
        Zplot = Z.T
        vmin = float(np.nanmin(Zplot))
        vmax = float(np.nanmax(Zplot))
        im = ax.imshow(
            Zplot,
            origin="lower",
            aspect="auto",
            extent=[ex.min(), ex.max(), em.min(), em.max()],
            cmap=cmap,
            vmin=vmin, vmax=vmax,
        )
        ax.set_title(shorten(title, width=28, placeholder="…"), fontsize=9)
        cb = plt.colorbar(im, ax=ax, fraction=0.06, pad=0.02)
        cb.ax.tick_params(labelsize=8)
        return im

    # layout sizes
    n_rows_main = len(main_rows)
    n_cols_main = len(col_order)

    n_cols_t0 = max(len(t0_ids), 1)
    n_cols_total = max(n_cols_main, n_cols_t0, 1)
    n_rows_total = n_rows_main + (1 if has_t0 else 0)

    fig_w = 3.2 * n_cols_total
    fig_h = 2.4 * max(n_rows_total, 1)

    fig = plt.figure(figsize=(fig_w, fig_h))
    gs = GridSpec(nrows=max(n_rows_total, 1), ncols=n_cols_total, figure=fig)

    row_centers = []
    labels = []
    row = 0

    # ---- T0 row (top) ----
    if has_t0:
        for c in range(len(t0_ids)):
            ax = fig.add_subplot(gs[row, c])
            plot_one(ax, t0_ids[c], t0_titles[c])  # T0 uses clean_title
            if c != 0:
                ax.tick_params(axis="y", labelleft=False)

        for c in range(len(t0_ids), n_cols_total):
            ax = fig.add_subplot(gs[row, c])
            ax.axis("off")

        bbox = gs[row, 0].get_position(fig)
        row_centers.append((bbox.y0 + bbox.y1) / 2)
        labels.append("T0")
        row += 1

    # ---- Main rows (T1.. etc.) ----
    for tp in main_rows:
        for c, pname in enumerate(col_order):
            ax = fig.add_subplot(gs[row, c])

            if (tp in grid.index) and (pname in grid.columns) and pd.notna(grid.loc[tp, pname]):
                i = int(grid.loc[tp, pname])
                plot_one(ax, i, pname)  # title is plot_name only
            else:
                ax.axis("off")
                continue

            if c != 0:
                ax.tick_params(axis="y", labelleft=False)
            if row != (n_rows_total - 1):
                ax.tick_params(axis="x", labelbottom=False)

        for c in range(n_cols_main, n_cols_total):
            ax = fig.add_subplot(gs[row, c])
            ax.axis("off")

        bbox = gs[row, 0].get_position(fig)
        row_centers.append((bbox.y0 + bbox.y1) / 2)
        labels.append(tp)
        row += 1

    # row labels on left
    for lab, yc in zip(labels, row_centers):
        fig.text(-0.01, yc, lab, va="center", ha="left", fontsize=12)

    # titles/labels
    if figure_title is None:
        figure_title = recycled_value
    fig.suptitle(figure_title, y=0.995, fontsize=18)

    fig.text(0.5, 0.02, "Excitation (nm)", ha="center", fontsize=10)
    fig.subplots_adjust(wspace=0.25, hspace=0.35, top=0.95, bottom=0.06, left=0.04, right=0.99)
    plt.show()


# ---- Make two parallel figures ----
plot_by_recycled(title_df, dataset_train, recycled_value="fresh", figure_title="Fresh")
plot_by_recycled(title_df, dataset_train, recycled_value="recyc", figure_title="Recycled")

import numpy as np
import pandas as pd
from eempy.plot import plot_fmax

def find_2d_mats(obj):
    mats = []
    for k, v in getattr(obj, "__dict__", {}).items():
        try:
            arr = np.asarray(v)
        except Exception:
            continue
        if arr.ndim == 2:
            mats.append((k, arr))
    return mats

def extract_scores_and_loadings(parafac, dataset):
    """
    Returns:
      scores: (n_samples, R)
      ex_load: (n_ex, R)
      em_load: (n_em, R)
    Works across eempy versions by matching shapes.
    """
    n_samples = dataset.eem_stack.shape[0]
    n_ex = len(dataset.ex_range)
    n_em = len(dataset.em_range)

    # gather candidate matrices from parafac and nested objects
    cand = find_2d_mats(parafac)
    for k, v in getattr(parafac, "__dict__", {}).items():
        cand += [(f"{k}.{kk}", arr) for kk, arr in find_2d_mats(v)]

    # find scores/loadings by shape
    ex_load = next((arr for _, arr in cand if arr.shape[0] == n_ex and arr.shape[1] >= 2), None)
    em_load = next((arr for _, arr in cand if arr.shape[0] == n_em and arr.shape[1] >= 2), None)
    scores  = next((arr for _, arr in cand if arr.shape[0] == n_samples and arr.shape[1] >= 2), None)

    # sometimes loadings are transposed (R, n_ex); handle that
    if ex_load is None:
        ex_load = next((arr.T for _, arr in cand if arr.shape[1] == n_ex and arr.shape[0] >= 2), None)
    if em_load is None:
        em_load = next((arr.T for _, arr in cand if arr.shape[1] == n_em and arr.shape[0] >= 2), None)
    if scores is None:
        scores = next((arr.T for _, arr in cand if arr.shape[1] == n_samples and arr.shape[0] >= 2), None)

    if ex_load is None or em_load is None or scores is None:
        # print helpful info
        print("Could not uniquely detect scores/loadings. Candidate shapes:")
        for name, arr in cand[:40]:
            print(name, arr.shape)
        raise AttributeError("Could not extract PARAFAC scores/loadings from this eempy PARAFAC object.")

    # R is the common number of components
    R = min(ex_load.shape[1], em_load.shape[1], scores.shape[1])
    return scores[:, :R], ex_load[:, :R], em_load[:, :R]

def compute_fmax_table(parafac, dataset):
    scores, ex_load, em_load = extract_scores_and_loadings(parafac, dataset)
    ex_max = np.max(ex_load, axis=0)   # (R,)
    em_max = np.max(em_load, axis=0)   # (R,)
    fmax = scores * (ex_max * em_max)  # (n_samples, R)

    cols = [f"C{i+1}_Fmax" for i in range(fmax.shape[1])]
    return pd.DataFrame(fmax, index=list(dataset.index), columns=cols)

fmax_table = compute_fmax_table(parafac, dataset_proc)
fmax_table.head()

df = fmax_table.reset_index().rename(columns={"index": "sample_name"})
# Split sample_name by "_"
parts = df["sample_name"].str.split("_", expand=True)

# Name the split columns (adjust count automatically)
parts.columns = [f"part_{i+1}" for i in range(parts.shape[1])]

# Combine into one organized table: sample_name + parts + Fmax columns
summary = pd.concat([df[["sample_name"]], parts, df[["C1_Fmax", "C2_Fmax", "C3_Fmax"]]], axis=1)
# keep only part_5..part_8 (note: these are 1-indexed in the column names we created)
keep_parts = [c for c in ["part_5", "part_6", "part_7", "part_8"] if c in parts.columns]

summary_keep = pd.concat(
    [parts[keep_parts], df[["C1_Fmax", "C2_Fmax", "C3_Fmax"]]],
    axis=1
)
summary_keep.loc[summary_keep["part_8"] == "redo", "part_8"] = np.nan
summary_keep["part_7"] = summary_keep["part_7"].replace({"arthro1": "arthro", "pseudo1": "pseudo"})

# 1) standardize time labels (part_5)
summary_keep["part_5"] = summary_keep["part_5"].astype(str).str.replace(r"^t4$", "T4", regex=True)
# more general (optional): make any leading 't' -> 'T' (t0,t1,t2...)
summary_keep["part_5"] = summary_keep["part_5"].str.replace(r"^t(\d+)$", r"T\1", regex=True)
# 3) rename columns
summary_keep = summary_keep.rename(columns={
    "part_5": "time",
    "part_6": "recycled",
    "part_7": "organism",
    "part_8": "oxygen",
})
# 2) keep only rows where time starts with "T"
Time_summary = summary_keep[summary_keep["time"].str.startswith("T", na=False)].copy()
standard = summary_keep[~summary_keep["time"].str.startswith("T", na=False)].copy()


standard

print(summary_keep['part_8'].unique())

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# -------------------------
# 0) Start from your Time_summary
# -------------------------
df = Time_summary.copy()

# Ensure types
df["time"] = df["time"].astype(str).str.upper().str.strip()
df["recycled"] = df["recycled"].astype(str).str.lower().str.strip()
df["organism"] = df["organism"].astype(str).str.lower().str.strip()
df["oxygen"] = df["oxygen"].astype(str)

# -------------------------
# 1) Fix T0 oxygen handling:
#    - for T0 rows, if oxygen is None/NaN -> set to "ana"
#    - duplicate those same T0 rows and set oxygen to "aer"
# -------------------------
df["oxygen"] = df["oxygen"].replace({"None": np.nan, "nan": np.nan, "NaN": np.nan})
is_t0 = df["time"].eq("T0")

# fill missing oxygen at T0 with "ana"
df.loc[is_t0 & df["oxygen"].isna(), "oxygen"] = "ana"

# duplicate T0 rows as aer (so T0 exists for both ana and aer)
t0_dup = df.loc[is_t0].copy()
t0_dup["oxygen"] = "aer"

df = pd.concat([df, t0_dup], ignore_index=True)

# Clean oxygen labels
df["oxygen"] = df["oxygen"].astype(str).str.lower().str.strip()

# -------------------------
# 2) Convert time T0..T5 to numeric 0..5
# -------------------------
df["time_num"] = df["time"].str.extract(r"T(\d+)", expand=False).astype(float)
df = df.dropna(subset=["time_num"]).copy()
df["time_num"] = df["time_num"].astype(int)

# keep only 0..5 if you want
df = df[df["time_num"].between(0, 5)].copy()

# -------------------------
# 3) Plot: 2 rows (fresh/recyc) x 3 cols (C1..C3)
#    - color by organism
#    - linestyle by oxygen (aer solid, ana dashed)
# -------------------------
components = ["C1_Fmax", "C2_Fmax", "C3_Fmax"]
row_levels = ["fresh", "recyc"]

organisms = sorted(df["organism"].dropna().unique())
oxygen_styles = {"aer": "-", "ana": "--"}  # dashed/solid by oxygen

TITLE_FS = 14
LABEL_FS = 12
TICK_FS  = 11

fig, axes = plt.subplots(
    nrows=2, ncols=3,
    figsize=(10, 6),
    sharex=True
)
# one consistent color per organism (uses matplotlib default color cycle)
default_colors = plt.rcParams["axes.prop_cycle"].by_key()["color"]
org_color = {org: default_colors[i % len(default_colors)] for i, org in enumerate(organisms)}

for r, rec in enumerate(row_levels):
    dfr = df[df["recycled"] == rec].copy()

    for c, comp in enumerate(components):
        ax = axes[r, c]

        for org in organisms:
            dforg = dfr[dfr["organism"] == org]

            for oxy, ls in oxygen_styles.items():
                sub = dforg[dforg["oxygen"] == oxy].sort_values("time_num")
                if sub.empty:
                    continue

                ax.plot(
                    sub["time_num"], sub[comp],
                    color=org_color[org],      # same color for this organism
                    linestyle=ls,              # dashed/solid by oxygen
                    marker="o",
                    label=f"{org} ({oxy})"
                )

        ax.set_title(comp)
        ax.set_xlim(0, 5)
        ax.set_xticks([0, 1, 2, 3, 4, 5])
        # After each ax.plot(...) block (inside your loop) set axis label/ticks/title sizes
        ax.set_title(comp, fontsize=TITLE_FS)
        ax.set_xlabel("Time", fontsize=LABEL_FS)          # only if you want per-axis; otherwise do bottom row only
        ax.set_ylabel(rec, fontsize=LABEL_FS)             # only first col; keep your existing logic
        ax.tick_params(axis="both", which="major", labelsize=TICK_FS)
        if c == 0:
            ax.set_ylabel(rec)

# x-axis label only on bottom row
for ax in axes[1, :]:
    ax.set_xlabel("Time points")

# One combined legend (outside)
handles, labels = axes[0, 0].get_legend_handles_labels()
fig.legend(handles, labels, loc="center left", bbox_to_anchor=(1.01, 0.5), frameon=False)

fig.tight_layout()
plt.show()

import numpy as np
import matplotlib.pyplot as plt
from textwrap import shorten
from eempy.plot import plot_eem_stack

prefix = "Data_BlankSub_Graph_S1_"

raw_titles = list(dataset_train.index)
clean_titles = [t[len(prefix):] if t.startswith(prefix) else t for t in raw_titles]

# keep ONLY samples whose cleaned title does NOT start with T/t
sel = [i for i, t in enumerate(clean_titles) if not t.lower().startswith("t")]

X = dataset_train.eem_stack[sel]
titles = [shorten(clean_titles[i], 28, placeholder="…") for i in sel]

n_cols = 6
n = len(sel)
n_rows = 2

out = plot_eem_stack(
    eem_stack=X,
    ex_range=np.asarray(dataset_train.ex_range),
    em_range=np.asarray(dataset_train.em_range),
    titles=titles,
    n_cols=n_cols,
    auto_intensity_range=True,
    cbar=True,
    cbar_fraction=0.04,
    figure_size=(14, 5),
    plot_x_axis_label=False,
    plot_y_axis_label=False,
)

fig = out[0]
try:
    fig.set_constrained_layout(False)
except Exception:
    pass

fig.subplots_adjust(wspace=0.1, hspace=0.1, top=0.95, bottom=0.06)
plt.show()

import numpy as np
import matplotlib.pyplot as plt

def plot_eem_panel(
    eems,                  # dict: {title: eem_matrix (n_ex, n_em)}
    ex_range, em_range,    # 1D arrays
    figsize=(22, 5),
    title_fontsize=16,
    label_fontsize=13,
    tick_fontsize=11,
    cmap="jet",
    vmin=None, vmax=None,  # set to None for autoscale; or pass numbers for consistent scaling
):
    names = list(eems.keys())
    mats = [np.asarray(eems[k]) for k in names]

    # If you want consistent color scaling across panels:
    if vmin is None:
        vmin = min(np.nanmin(m) for m in mats)
    if vmax is None:
        vmax = max(np.nanmax(m) for m in mats)

    fig, axes = plt.subplots(
        1, len(names),
        figsize=figsize,
        constrained_layout=True,
        sharex=True, sharey=True
    )

    if len(names) == 1:
        axes = [axes]

    # pcolormesh coordinate edges (makes axes match wavelengths cleanly)
    # If your ex/em are evenly spaced, this works well:
    ex = np.asarray(ex_range)
    em = np.asarray(em_range)

    # Build edges for pcolormesh
    def edges(x):
        x = np.asarray(x)
        dx = np.diff(x)
        # assume roughly regular spacing; extend ends
        left = x[0] - dx[0]/2
        right = x[-1] + dx[-1]/2
        mid = x[:-1] + dx/2
        return np.concatenate([[left], mid, [right]])

    ex_edges = edges(ex)
    em_edges = edges(em)

    im = None
    for ax, name, Z in zip(axes, names, mats):
        # Z is (n_ex, n_em), so x-axis = emission, y-axis = excitation
        im = ax.pcolormesh(em_edges, ex_edges, Z, shading="auto", cmap=cmap, vmin=vmin, vmax=vmax)

        ax.set_title(name, fontsize=title_fontsize, pad=8)
        ax.tick_params(axis="both", labelsize=tick_fontsize)

    # Shared axis labels
    axes[0].set_ylabel("Excitation (nm)", fontsize=label_fontsize)
    for ax in axes:
        ax.set_xlabel("Emission (nm)", fontsize=label_fontsize)

    # One shared colorbar
    cbar = fig.colorbar(im, ax=axes, shrink=0.9, pad=0.02)
    cbar.set_label("Intensity (a.u.)", fontsize=label_fontsize)
    cbar.ax.tick_params(labelsize=tick_fontsize)

    plt.show()